### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by atherdon** [inessadl/video-app#2]
Hi @inessadl, i find this repository and decided to write you a message. My name is Arthur and I'm a founder of a small startup(Groceristar). Will you be interested to contribute to our open source projects and gain some experience in startup?
This is accounts of our organizations: [ChickenKyiv](https://github.com/ChickenKyiv) and [Groceristar](https://github.com/GroceriStar)
This is our AngelList account: https://angel.co/groceristar
This is our Medium blog: https://medium.com/groceristar

Tell me what do you think,
Arthur

**Comment by inessadl** [comment]
Hello @atherdon, thank you for the contact, but at the moment I'm already involved in other projects.
